INSERT IGNORE INTO curso(codigo,nombre) VALUES ('28','Social Humanística 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='28' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3003','Área Social Humanística 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3003' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='28' AND a.codigo='3003';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('29','Social Humanística 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='29' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3011','Área Social Humanística 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3011' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='29' AND a.codigo='3011';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('72','Física Básica');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='72' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3007','Física Básica');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3007' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='72' AND a.codigo='3007';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('146','Física 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='146' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3014','Física 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3014' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='146' AND a.codigo='3014';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('169','Matemática Básica 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='169' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3000','Área Matemática Básica 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3000' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='169' AND a.codigo='3000';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('170','Matemática Básica 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='170' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3006','Área Matemática Básica 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3006' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='170' AND a.codigo='3006';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2667','Técnicas de Investigación y Estudio');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2667' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3005','Técnicas de Estudio e Investigación');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3005' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2667' AND a.codigo='3005';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('290','Matemática Intermedia 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='290' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3013','Área Matemática Intermedia 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3013' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,95.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='290' AND a.codigo='3013';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('291','Matemática Intermedia 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='291' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3021','Área Matemática Intermedia 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3021' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,95.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='291' AND a.codigo='3021';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('292','Matemática Intermedia 3');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='292' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3022','Área Matemática Intermedia 3');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3022' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,95.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='292' AND a.codigo='3022';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('674','Matemática Aplicada 3');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='674' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3027','Matemática Aplicada 3');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3027' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,95.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='674' AND a.codigo='3027';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('673','Matemática Aplicada 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='673' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3028','Matemática Aplicada 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3028' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,95.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='673' AND a.codigo='3028';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('147','Física 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='147' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3023','Física 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3023' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,97.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='147' AND a.codigo='3023';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('177','Deportes 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='177' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3082','Deportes 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3082' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='177' AND a.codigo='3082';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('178','Deportes 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='178' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3086','Deportes 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3086' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='178' AND a.codigo='3086';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2795','Matemática de Cómputo 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2795' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3231','Matemática para Computación 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3231' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2795' AND a.codigo='3231';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2796','Introducción a la Programación y Computación 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2796' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3234','Introducción a la Programación y Computación 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3234' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2796' AND a.codigo='3234';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2797','Lógica de Sistemas');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2797' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3232','Lógica de Sistemas');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3232' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2797' AND a.codigo='3232';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('949','Estadística 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='949' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3090','Estadística 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3090' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='949' AND a.codigo='3090';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2799','Matemática de Cómputo 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2799' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3233','Matemática para Computación 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3233' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2799' AND a.codigo='3233';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2800','Introducción a la Programación y Computación 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2800' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3236','Introducción a la Programación y Computación 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3236' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2800' AND a.codigo='3236';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2803','Organización de Lenguajes y Compiladores 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2803' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3239','Organización de Lenguajes y Compiladores 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3239' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2803' AND a.codigo='3239';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2804','Organización Computacional');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2804' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3240','Organización Computacional');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3240' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2804' AND a.codigo='3240';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2805','Estructura de Datos');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2805' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3241','Estructura de Datos');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3241' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2805' AND a.codigo='3241';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2807','Práctica Inicial TI');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2807' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3238','Prácticas Iniciales');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3238' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2807' AND a.codigo='3238';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('685','Investigación de Operaciones 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='685' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3243','Investigación de Operaciones 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3243' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='685' AND a.codigo='3243';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2809','Economía');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2809' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3244','Economía');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3244' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2809' AND a.codigo='3244';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2810','Organización de Lenguajes y Compiladores 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2810' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3245','Organización de Lenguajes y Compiladores 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3245' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2810' AND a.codigo='3245';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2811','Arquitectura de Computadores y Ensambladores 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2811' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3246','Arquitectura de Computadoras y Ensambladores 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3246' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2811' AND a.codigo='3246';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2812','Manejo e Implementación de Archivos');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2812' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3247','Manejo e Implementación de Archivos');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3247' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2812' AND a.codigo='3247';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('795','Investigación de Operaciones 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='795' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3249','Investigación de Operaciones 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3249' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='795' AND a.codigo='3249';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2813','Teoría de Sistemas 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2813' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3248','Teoría de Sistemas 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3248' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2813' AND a.codigo='3248';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2814','Sistemas Operativos 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2814' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3250','Sistemas Operativos 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3250' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2814' AND a.codigo='3250';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2816','Redes de Computadoras 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2816' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3252','Redes de Computadoras 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3252' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2816' AND a.codigo='3252';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2817','Sistemas de Bases de Datos 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2817' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3253','Sistemas de Bases de Datos 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3253' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2817' AND a.codigo='3253';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2818','Práctica Intermedia TI');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2818' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3254','Prácticas Intermedias');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3254' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2818' AND a.codigo='3254';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2815','Arquitectura de Computadores y Ensambladores 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2815' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3251','Arquitectura de Computadoras y Ensambladores 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3251' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2815' AND a.codigo='3251';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2821','Sistemas de Bases de Datos 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2821' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3257','Sistemas de Bases de Datos 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3257' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2821' AND a.codigo='3257';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2819','Sistemas Operativos 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2819' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3255','Sistemas Operativos 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3255' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2819' AND a.codigo='3255';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2820','Redes de Computadoras 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2820' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3256','Redes de Computadoras 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3256' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2820' AND a.codigo='3256';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2822','Análisis y Diseño de Sistemas 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2822' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3258','Análisis y Diseño de Sistemas 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3258' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2822' AND a.codigo='3258';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2823','Seminario de Sistemas 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2823' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3259','Seminario de Sistemas 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3259' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2823' AND a.codigo='3259';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2824','Modelación y Simulación 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2824' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3260','Modelación y Simulación 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3260' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2824' AND a.codigo='3260';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2825','Sistemas Organizacionales y Gerenciales 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2825' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3261','Sistemas Organizacionales y Gerenciales 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3261' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2825' AND a.codigo='3261';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2826','Inteligencia Artificial');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2826' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3262','Inteligencia Artificial 1');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3262' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,90.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2826' AND a.codigo='3262';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2827','Análisis y Diseño de Sistemas 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2827' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3264','Análisis y Diseño de Sistemas 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3264' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2827' AND a.codigo='3264';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2828','Seminario de Sistemas 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2828' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3265','Seminario de Sistemas 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3265' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2828' AND a.codigo='3265';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2829','Práctica Final');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2829' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3268','Prácticas Finales Ingeniería en Ciencia y Sistemas');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3268' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2829' AND a.codigo='3268';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2834','Sistemas Organizacionales y Gerenciales 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2834' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3270','Sistemas Organizacionales y Gerenciales 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3270' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2834' AND a.codigo='3270';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2835','Modelación y Simulación 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2835' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3269','Modelación y Simulación 2');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3269' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2835' AND a.codigo='3269';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2836','Software Avanzado');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2836' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3274','Software Avanzado');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3274' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2836' AND a.codigo='3274';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('2837','Seminario de Investigación');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='2837' AND p.codigo='2016-56';
INSERT IGNORE INTO curso(codigo,nombre) VALUES ('3278','Seminario de Investigación');
INSERT IGNORE INTO pensum_curso(id_curso,id_pensum,semestre) SELECT c.id,p.id,NULL FROM curso c CROSS JOIN pensum p WHERE c.codigo='3278' AND p.codigo='2025-58';
INSERT IGNORE INTO equivalencia_curso(id_curso_de,id_curso_a,porcentaje,opinion) SELECT d.id,a.id,100.0,'EQUIVALENTE' FROM curso d CROSS JOIN curso a WHERE d.codigo='2837' AND a.codigo='3278';
